### ISSUE TITLE
Add a ~/.karton/config-dirs

### ISSUE THREAD

**Issue by tychosoft** [karton/karton#1]
The only use of the target directory of the create image seems to be to create a place to store the image config, as per "howto" example; karton image create work ~/work-ubuntu-devel-image

Specifying arbitrary target directories just to hold a "definitions.py" file seems a complete waste and unneeded pollution of the user visible file system.  If the target directory were actually used for something more than just that, or otherwise auto-mapped into the home I might have felt differently.

There already is a ~/.karton/home-dirs/{image}/ path, and by extension, I think a far better use would be to have a ~/.karton/config-dirs/{image}/ path, and not bother the user with this at all.

**Comment by barisione** [comment]
The definition dir is a directory and not a file because I will add the ability to copy files into an image so these files needs a place where to be.

While I understand your point, I'm afraid that hiding the definition file in a hidden directory will make it difficult to find for the user.
The difference with the home directory is that a normal user may never need to modify on the host the content of the image home directory.

**Comment by tychosoft** [comment]
@barisione  in my own use case I simply map local directories from my home into the container's home as needed, and use those to move/share things between host and container.  I also like that the container homes are hidden ~/.karton/home-dirs/ directories because I think they should otherwise only be manipulated thru the container.  Of course I am thinking of a rather different use case than what many may choose, as I think of karton as a quick access complete distro specific development & build environment, rather than as a way to run commands and debug apps in the host env.  For example, I keep the source checkouts, ~/src directory, and builds entirely private in the container homes and use it as a complete alternate environment.  I only share a ~/tmp for moving things around, the ~/Downloads directory for convenience, and my ~/.ssh.

To me, when I was playing with it, I was thinking of the definition as being conceptually more like an apache /etc/conf.d type thing, which is why I think of it belonging under ~/.karton rather than outside.  In fact, I would have taken a very different approach for the question of making user access easier, and like with "crontab -e", would have chosen something like a "karton edit image-name" with associated automatic build after, and keep the definitions in a ~/.karton/config/ with each named by the images rather than "definition".  But similarly to having a different use case than most likely do, I also have a strong bias for writing system services rather than user apps, so I probably look at it rather differently, and I also did not know you had other uses planned.

**Comment by tychosoft** [comment]
@barisione  I probably should further explain I do have two other rather specialized use cases in mind that I doubt most people would do, and hence why I am particularly interested in karton at the moment.  The first is to create a debian package build engine/environment that I can automate and run under the control of the host env.  This for me is very useful as I can run the desktop distro of my choice and still support backend package production off my dev machine (as well as development and testing within the container as already noted).  The other is to use gitlab ci runners.  Since all these uses require setting up a distro for development in the same manner anyway, this means I can use one instance for all these missions rather than having to setup a complete distro with a full dev env in docker for gitlab-ci, and then have to do the same all over again in a completely separate environment for a chroot builder & for development testing.

**Comment by barisione** [comment]
I added the ability to copy files into an image, see #6, so we definetely need directories, not just files (`props.copy('foo.bar', '/xxx/yyy/foo.bar')` copies the relative path `foo.bar` from inside the definition directory).

I thought about moving direcories like you suggested, but I personally much prefer having them separate so people can keep their definition files together with the project they relate. For instance you could have your work repos in `~/src/work/` and the definition in `~/src/work/karton-image/` or something like that.

Doing something like `crontab -e` would mean more problems with opening the default editor and ending up opening vim by default (which some people cannot operate).

Nothing prevents you from putting everything in a hidden place so it doesn't bother you.
