### ISSUE TITLE
Installed packages with apt-get or apt are not persistent.

### ISSUE THREAD

**Issue by DiegoMagdaIeno** [karton/karton#14]
I don't know if this is intended behaviour 

But only the apps I install  with the props.packages([etc]) are persistent, for example if I do `sudo apt-get install git ` and I reboot my Mac, app seems to get deleted, is this intended?

Btw my Mac:

```
ProductName:	Mac OS X
ProductVersion:	10.15
BuildVersion:	19A582a
```

**Comment by barisione** [comment]
The idea is that what you do to an image is transient and will last until the image is stopped (`karton stop IMAGE-NAME`) and restarted (`karton start IMAGE-NAME` or implicitly by running a command).
As an implementation detail, this is achieved by keeping a Docker image running with a program in it which just sleeps.

When you reboot, the Karton/Docker image is discarded so, after restart, you will have a new one.
It would be nice to not lose images across reboots but only when you explicitly stop them, but that's not possible with Docker.
