### ISSUE TITLE
Unable to build image

### ISSUE THREAD

**Issue by acruzpr** [karton/karton#3]
I was trying to build an ubuntu image on Mac, but  got the following error:

Step 8/16 : COPY sudoers /etc/sudoers
 ---> Using cache
 ---> aa23a5f4a573
Step 9/16 : RUN chmod 440 /etc/sudoers
 ---> Using cache
 ---> 8c398726ef84
failed to process "/karton/session_runner.py'": unexpected end of statement while looking for matching single-quote

Failed to run "karton build" command:
Command '['docker', 'build', '--tag', 'research', '/var/folders/3b/kkt2yj0d04q0q7bm9rxpm5cr0000gp/T/io.github.karton/builder/research-2mypo2']' returned non-zero exit status 1
No update check was run.

How to solve the problem?

Thanks!

**Comment by barisione** [comment]
I had the same problem over the weekend. The stray quote has always been there, I just think the Docker parser was not very strict but was changed recently.
Fixed in 449f74e38b81db425b6a06ddf7c3fe95010e4dcc. I will make a release very soon.

**Comment by barisione** [comment]
Released.
